### ISSUE TITLE
How to turn on debug log in plugin

### ISSUE THREAD

**Issue by xn-zhao** [apache/trafficserver#10846]
Hi all,
I found that there are many plugins, like cache_range_requests support the DEBUG_LOG.
How can we turn this DEBUG_LOG in our configuration after installing ATS?
Thanks.

**Comment by brbzull0** [comment]
Hi. 
You have to [enable](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.yaml.en.html#proxy-config-diags-debug-enabled) debug logs and specify the [tag](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.yaml.en.html#proxy-config-diags-debug-tags). The cache_range_request debug tag seems to be the plugin name(usually is).

Not sure which ATS version are you using but if you are building out of master, then you have a `.yaml` file, otherwise you have a `.config` file.

`records.config` set the following two config records to:
```
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING cache_range_requests
```

`records.yaml` run the following command( or edit the file manually)
```
traffic_ctl config set  proxy.config.diags.debug.enabled 1 --cold
traffic_ctl config set  proxy.config.diags.debug.tags cache_range_requests --cold
```
Thanks.

**Comment by xn-zhao** [comment]
Thanks a lot, @brbzull0 !
Let me try your instruction.

**Comment by bryancall** [comment]
@xn-zhao Did this resolve your issue?  If so, can you please close it.
