### ISSUE TITLE
ATS 10.0.x, how to set cache inspector ?

### ISSUE THREAD

**Issue by Solarisbf** [apache/trafficserver#11652]
hi

i would like to set cache inspector on ATS 10.0.x

but i cannot find any configurations on records.yaml

i found `proxy.config.http_ui_enabled` option for setting cache inspector up on ATS 9.2.x documentation

and could set this

**### 1. please let me know how to setup cache inspector on ATS 10.0.x** 

maybe there is cache inspector hidden on ATS 10.0.x

https://docs.trafficserver.apache.org/en/10.0.x/admin-guide/storage/index.en.html#inspecting-the-cache

**### 2. or does it deprecated on ATS 10.0.x ?**

thx a  lot

@bryancall @sekimura @janfrode @calavera @biilmann @jpeach

**Comment by bneradt** [comment]
Thank you for the issue with these questions.

Cache inspector was removed from ATS 10 via:
https://github.com/apache/trafficserver/pull/10710

The Cache inspector tools was generally considered not updated well and that we were better off removing a poorly maintained tool. Just to document it, there was a mailing list proposal about this with subject: `[PROPOSAL] Remove the old HTTP stats and cache inspection pages`

I'll remove that section you referenced since I think it just got missed from that cleanup.

**Comment by bneradt** [comment]
Doc update to remove the rest of cache inspector references:
https://github.com/apache/trafficserver/pull/11656

**Comment by bneradt** [comment]
Cleaning up by closing the issue since the question is answered and the docs are updated from the feedback provided in this issue. Thank you for filing @Solarisbf .

**Comment by Solarisbf** [comment]
thx a lot !!! @bneradt
