### ISSUE TITLE
ATS 10 traffic_ctl doesn't get a warning when you don't have permissions

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#11725]
On a production host I am not seeing a warning when I don't have permissions and I am trying to set a config option:

```
[bcall@e5 trafficserver]$ /opt/edge/1.1/trafficserver/10.0/bin/traffic_ctl config set proxy.config.http.connect.down.policy 0
[bcall@e5 trafficserver]$
```

**Comment by brbzull0** [comment]
Just tested this, the error itself is that  ATS is not respoding with the right error response:
```bash
$ traffic_ctl config set proxy.config.diags.debug.tags "http.*|dns.*"
Server Error found:
[10] Unauthorized action
- [2] Denied privileged API access for uid=105106 gid=100
```
in any case the record is **not set** unless you use `sudo` which is ok, so no harm will be done.
The issue was introduced by https://github.com/apache/trafficserver/pull/10986 few months ago.

I'll make a patch for this.
