### ISSUE TITLE
Build fail with BoringSSL

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#1437]
I'm trying build TS with BoringSSL, but I got this.

```
BIO_fastopen.cc:76:9: error: use of undeclared identifier 'BIO_sock_non_fatal_error'
    if (BIO_sock_non_fatal_error(errno)) {
        ^
BIO_fastopen.cc:99:9: error: use of undeclared identifier 'BIO_sock_non_fatal_error'
    if (BIO_sock_non_fatal_error(errno)) {
        ^
2 errors generated.
```

BoringSSL doesn't have `BIO_sock_non_fatal_error`. `bio_fd_non_fatal_error` looks similar API, but it is internal API.

**Comment by jablko** [comment]
Hmm -- I see what you mean -- BoringSSL sock_read() and sock_write() have used bio_fd_non_fatal_error() since [1], which claims to be a fork from https://github.com/openssl/openssl/commit/30ea570f0fb2717b1faca5d611a3ab200c8eac83, however in OpenSSL, they've used BIO_sock_non_fatal_error() since their inception -- and in particular in https://github.com/openssl/openssl/commit/30ea570f0fb2717b1faca5d611a3ab200c8eac83 [2]. I wonder why BoringSSL made this change?

So for fastopen_bread() and fastopen_bwrite(), BIO_sock_non_fatal_error() is correct, and I'm tempted to just copy it from OpenSSL, for implementations that lack it (BoringSSL)?

[1] https://boringssl.googlesource.com/boringssl/+/95c29f3cd1f6c08c6c0927868683392eea727ccb
[2] https://github.com/openssl/openssl/blob/30ea570f0fb2717b1faca5d611a3ab200c8eac83/crypto/bio/bss_sock.c
