### ISSUE TITLE
There should be a Cache-Control immutable constant in the API

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1484]
We could call it `TS_HTTP_VALUE_IMMUTABLE`.

See https://tools.ietf.org/html/draft-mcmanus-immutable-01 for the RFC draft.

**Comment by zwoop** [comment]
Well, more than just having the constant, we really need to think about the implications of this, and how we should handle immutable in the cache. Today, we have configurations to basically achieve "immutable", such that clients can't force a refresh.  Interacting with this new CC: immutable would give this control back to the origin server instead of configurations on ATS (which is a good thing, at least in reverse proxies).

**Comment by bryancall** [comment]
The browser and origins handle immutable.  If you want to override the origin the header can be added with header_rewrite.
