### ISSUE TITLE
Assertion failing when calling TSHttpTxnReenable from another thread.

### ISSUE THREAD

**Issue by clearswift** [apache/trafficserver#1598]
See the attached example plugin. This hooks onto the `TS_HTTP_READ_RESPONSE_HDR_HOOK` hook and, on that event, launches a thread that re-enables the transaction. This fails the assertion `ink_release_assert(!server_vc || !client_vc || server_vc->thread == client_vc->thread);` on line 5933 in HttpSM.cc when making multiple connections.

A simple test of this is to browse any reasonably substantial web page (I used bbc.co.uk) through the proxy with this plugin enabled. Removing the assertion allows the page to load successfully.

So why is the assertion there? What's the issue with the client and server threads being different? As I said, removing the assertion makes things work but is there some corner case where this matters?

Alternatively, is the plugin wrong? Is it allowed to call TSHttpTxnReenable from a different thread? Is there a better way to do this?

[ThreadTestPlugin.zip](https://github.com/apache/trafficserver/files/855468/ThreadTestPlugin.zip)

**Comment by jpeach** [comment]
You have to call `TSHttpTxnReenable` from an event thread. The typical pattern is to use `TSContSchedule` to bounce the call back over to the event thread pool once you are done.

**Comment by clearswift** [comment]
I've tried that (and quite a few different things) and had the same result. The example was intended to be as minimal as possible.

There is an example plugin (examples/thread-1) that does the same thing as my example except that it uses a request related hook (OS_DNS). It doesn't use TSContSchedule to re-enable the transaction, but just does it in the thread function.

**Comment by oschaaf** [comment]
@keesspoelstra

**Comment by clearswift** [comment]
As an update, I've found that setting the proxy.config.http.server_session_sharing.pool config parameter to "global" seems to fix the issue (that is, I haven't seen the assertion fail since).

**Comment by keesspoelstra** [comment]
We've seen this also, it is possible for the statemachine to release the server_session to the wrong thread pool. 
In the case of TS_HTTP_READ_RESPONSE_HDR_HOOK, all response data can be present in the buffers. 
Upon TSHttpTxnReenable on a different thread ATS will dive into recursion, handle the response body and release the server_session to the session pool to the sessionpool on the wrong thread.
When the session is acquired again from the wrong session pool in the next request the assertion fires, the server_vc will not be migrated to the new thread, as it will do when the configuration is global instead of thread.

Also see:  https://github.com/apache/trafficserver/blob/master/proxy/http/HttpSessionManager.cc#L316

The releases should either be scheduled on the original thread (to guarantee that the session pools on the different threads do not overflow) or the server_vc should be moved to the new thread.

I'll try to prepare a fix which at least migrates the server_vc this week.

**Comment by bryancall** [comment]
I believe the new thread affinity API changes should fix this issue.  If this is still an issue please reopen.
