### ISSUE TITLE
proxy.config.ssl.server.multicert.exit_on_load_fail not documented

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#1602]
Not sure when proxy.config.ssl.server.multicert.exit_on_load_fail was added, but its not documented.

What does it do? Is it reloadable?

**Comment by zwoop** [comment]
Not reloadable. The setting restores the old/expected behavior, meaning

1. It will not let you start traffic_server with a bad ssl_multicert.config
2. It will not replace a running, functional configuration with a  broken ssl_multicert.config

I honestly don't know how we made this "off" by default, but I've filed an issue already to make the default for this to be "1" for v8.0.0.
