### ISSUE TITLE
header_rewrite Variable expansion doesn't work.

### ISSUE THREAD

**Issue by Ufoton** [apache/trafficserver#1737]
```
plugin.config
header_rewrite.so x-forwarded-host.config

x-forwarded-host.config
cond %{READ_REQUEST_HDR_HOOK}
        set-header X-Forwarded-Host %{HEADER:Host}
        set-header X-Forwarded-Proto https
        set-header X-Forwarded-Proto1 %<proto>

Expected result: Request to origin with headers 
X-Forwarded-Host www.example.com
X-Forwarded-Proto https
X-Forwarded-Proto1 https

Actual result
X-Forwarded-Host www.example.com
X-Forwarded-Proto https
X-Forwarded-Proto1 %

Same result with all Variable expansion.
Server version tested 6.2.1, 7.0.0
OS: Linux X64
```

**Comment by d2r** [comment]
The documentation needs fixing. In the config, we must enclose the expansion variable with double quotes like `"%<proto>"`.

The issue is that the characters `= < >` [are handled](https://github.com/apache/trafficserver/blob/36c68bbb3266650e6e09c34fd5fcfed3858f7331/plugins/header_rewrite/parser.cc#L43-L49) by the parser as conditional operators, and encountering `... %<proto>` results in tokens `{..., "%", "proto"}`. Subsequently, the `%` alone [is not recognizable](https://github.com/apache/trafficserver/blob/36c68bbb3266650e6e09c34fd5fcfed3858f7331/plugins/header_rewrite/expander.cc#L42-L45) by the expander as a variable that needs expanding.

Enclosing in quotes `"` results in the string contained within the quotes to be parsed as a single token, and this then can be recognized later by the expander.

I can update the documentation to reflect this.
