### ISSUE TITLE
Cache design

### ISSUE THREAD

**Issue by anhldbk** [apache/trafficserver#1916]
I'm reading the documentation about [Cache Layout](https://docs.trafficserver.apache.org/en/latest/developer-guide/cache-architecture/architecture.en.html#cache-layout)

> Traffic Server treats its persisent storage as an undifferentiated collection of bytes, assuming no other structure to it. In particular, it does not use the file system of the host operating system.

I think we can persist caches in the following naive way:
+ Use a big file storing cached objects sequentially 
+ Get data of each object via (offset, size) pairs
+ We may use `Zero Copy` to efficiently transfer data back to requesting clients. But `Zero Copy` comes with the cost of [not being able to support HTTPs or HTTP/2](https://news.ycombinator.com/item?id=10983331). Please correct me if I'm wrong.

(a more advanced way can be using LSM Tree found in the design of Rocksdb)

Please tell me the reason why ATS does NOT employ file system? Any advantage ?

**Comment by mlibbey** [comment]
ATS disk cache is already persistent -- restart the machine or ATS process, and when ATS comes back up, the cache is still there and in use. Have a disk fail, and the other disks' are still usable.

**Comment by anhldbk** [comment]
@mlibbey What do you think about using `LSM Tree`? Any better performance (and in which case) ?

**Comment by mlibbey** [comment]
@SolidWallOfCode would be way better equipped to answer than me.

**Comment by jpeach** [comment]
@anhldbk I think you need to start with a problem rather than a solution. There are clearly many different ways of implementing a persistent cache, each with strengths and weaknesses. If you identify a problem with the current implementation, that's a better way to focus a discussion.

**Comment by anhldbk** [comment]
@jpeach You're right! Currently I'm conducting a research on designing persistent caches. Sorry for my limited knowledge, but I'll be happy if you help me to answer the question above.

**Comment by jpeach** [comment]
Ah, thanks for clarifying @anhldbk. I think the [dev@](http://mail-archives.apache.org/mod_mbox/trafficserver-dev/) mailing list might be a better forum for this discussion.

FWIW you can find the original Inktomi patents that describe the cache design, which may be interesting for historical research purposes. I'm given to understand that the current implementation is much simplified from the original design based on performance results.

Since this isn't a code or implementation issue, I'm going to close this out. Please bring the discussion to the mailing list if you would like to continue,

**Comment by anhldbk** [comment]
@jpeach Perfect! Thank you for letting me know.
