### ISSUE TITLE
Splitting large objects into multiple fragments

### ISSUE THREAD

**Issue by anhldbk** [apache/trafficserver#2023]
Hi guys,

I'm reading documentation about [Object Structure](https://docs.trafficserver.apache.org/en/latest/developer-guide/cache-architecture/architecture.en.html#object-structure). Would you please tell me what does the bold phrase below really mean? It's better if there's an illustration here.

> Large objects are split in to multiple fragments when written to the cache. This is indicated by a total document length that is longer than the content in first Doc or an earliest Doc. In such a case a fragment offset table is stored. **This contains the byte offset in the object content of the first byte of content data for each fragment past the first (as the offset for the first is always zero).**

**Comment by SolidWallOfCode** [comment]
The fragment table is an array that is effectively indexed from 1..N-1 where N is the total number of fragments for the object. Each entry is a byte offset into the object content. Each fragment past the first* (earliest) fragment starts at a specific byte offset in the content for the object. E.g. if the first fragment is 1048576 bytes long, the second fragment has an offset of 1048576 because the first byte of the second fragment is 1048576 bytes from the start of the object content. This is the value stored in the fragment table. This enables fast determination of the correct fragment for a specific content offset which is used for handling range requests.

* Which by definition has an offset of 0 and so doesn't need to be stored.

**Comment by anhldbk** [comment]
@SolidWallOfCode Perfect! I think your explanation is much better than one in the document. Please make a PR against this issue.

Another related question, please! The data for an entire stored object may reside within a single fragment, or may be stored within multiple fragments that may reside in multiple stripes. So a fragment contains only data of a single object, right?

Please correct me if I'm wrong.

**Comment by anhldbk** [comment]
I see. There's a one-to-one relation between a fragment and an object.

**Comment by mlibbey** [comment]
@anhldbk -- want to take a crack at improving that documentation with what you learned from solidwallofcode?

**Comment by anhldbk** [comment]
@mlibbey You mean a PR, right? :1st_place_medal:
