### ISSUE TITLE
Figure out why non persistent statistics might be sticking around.

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#2059]
In PR #2040 I applied a band-aid to clear non-persistent HTTP2 statistics on start up.  In some crash cases, the stats seemed to be sticky, so I applied the same clearing we were doing with non persistent HTTP stats.

We should figure out what is going on, and apply the fix at a more fundamental layer.

**Comment by CrendKing** [comment]
Here is what we encountered about this issue recently in LinkedIn. Our ATS version is 6.2.x at this moment.

It seems that ATS maintains the stat values and stat name to stat ID map in the `traffic_manager` process, instead of the `traffic_server process`. It is probably designed this way to make sure stats survives `traffic_server` restarts. It is expected that every time the server restarts, all plugins would re-create the stats.

However, one of our plugin can't do static stat creation during initialization phase. This is because most of the stats are associated with URL segment from client request, which are only encountered during runtime (`TSRemapDoRemap()`). The plugin's logic can be summarized as
```
stat_name = create_stat_name(url_fragment[1]);
stat_id = find_stat_id_by_name(stat_name);
if (stat_id != 0) {
  stat_id = create_stat(stat_name, NON_PERSISTENT);
}
increment_stat_value(stat_id, 1);
```
If `traffic_server` process is dead for whatever reason (OOM, kill by user, by deployment system, etc.), it is restarted by the `traffic_manager`, but `find_stat_id_by_name` still returns the stat ID created by the previous process, since the mapping is maintained in `traffic_manager`, which did not restart. At this moment, it seems the new `traffic_server` process will not correctly increment the old stat ID, resulting the last line effectively no-op.

The simple solution is to change the stat from non-persistent to persistent. Once the `traffic_server` process is restarted, the stat value will be reset to 0, and the new process will correctly increment its value.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
