### ISSUE TITLE
Logging client HTTP protocol

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#2192]
We have been overloading pitag to log information about whether the client was coming from spdy or http2 or regular http.  This logic is gone in 7.1/master.  Since the http2 support isn't a plugin, cramming that into pitag isn't write.

There is an existing client request http version logging field (cqhv).  Currently it just pulls the http field out of the HttpSM which is either HTTP/1.0 or HTTP/1.1.  Should we expand that field to log HTTP/2 if the request came from a HTTP/2 session?  Should we add yet another logging field?

**Comment by maskit** [comment]
I think we should expand `cqhv` field if we keep the field. Current output is wrong because the field is not "a HTTP version ATS internally used". Also, HTTP layer on QUIC is not "HTTP/2" but currently it is described as "HTTP/QUIC" on the draft specification. So, it's still looks like a version of HTTP. We should be able to use the field for a few more years.

On the other hand, there's no guarantee that next protocol will be another version of HTTP. So, I think we should rely on client request protocol and version field (`cqpv`) instead (unless your real concern is versions of *HTTP*).

**Comment by shinrich** [comment]
Splendid!  It looks like cqpv already does exactly what we need.  It leverages off of the ProxyClientSession->get_protocol_string() call.  It either prints http/2, http/1.0, or http/1.1
