### ISSUE TITLE
Ability to add contextual data on (Net)VConnections

### ISSUE THREAD

**Issue by keesspoelstra** [apache/trafficserver#2388]
As there are hooks on the NetVConnection level it makes sense to be able to store contextual data on it from the plugins perspective.
Proposed are:
TSVConnArgIndexReserve
TSVConnArgSet
TSVConnArgGet
TSVConnArgIndexNameLookup
TSVConnArgIndexLookup

In combination with https://github.com/apache/trafficserver/issues/2380 We should be able to handle the lifecycle of said objects set with these TSVConnArg* functions.

Do we only want this on NetVConnections or on all VConnections? Having this on VConnections might be overkill memorywise.

**Comment by Enteee** [comment]
until this is implemented: As a TSVConn is technically a TSCont, is it possible for a plugin to add data to a TSVConn using TSContDataSet / -Get?

**Comment by keesspoelstra** [comment]
I think using TSContDataSet/Get will not work as that is being applied to INKContInternal continuations.
The internal entities aren't derived from INKContInternal.

**Comment by SolidWallOfCode** [comment]
I think this is reasonable and useful, particularly if the array size can be set at build time. I agree that it should be just at the `NetVConnection` level, not at `VConnection` because `NetVConnection` is special in many ways compared to `VConnection`. What I would recommend is writing this up in Sphinx format as a man page similar to [TSHttpArgs](https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSHttpArgs.en.html) and post that to the dev mailing list with a reference to this page for discussion. The write up would both make it clear what the API was and provide ready to use documentation if accepted.

**Comment by SolidWallOfCode** [comment]
@Enteee - I think that should work for you but it wouldn't do what @keesspoelstra wants to do. `INKVConnInternal` (nee `TSVConn`) is a subclass of `INKContInternal` (nee `TSCont`) and so I would expect it to work. It does bring up the issue that `TSVConn` is just a wrapper that forwards to a `VConnection` and it will frequently be the case that the  `VConnection` is not a `NetVConnection`. How will these functions deal with that? Perhaps we want another wrapper subclass that is `NetVConnection` oriented?

**Comment by keesspoelstra** [comment]
We could also do it on the VConnections by dynamically allocating storage for the args. 
I expect the number of use cases for VConnections to be much smaller than NetVConnections so the hit for allocating this memory on demand might not be too big when used. 

I think lifecycle handling (ensuring close/end) is a bit harder (or more work) on the VConnections though...

I'd still put the storage for NetVConnections in the class itself though.

TSContDataSet is potentially dangerous as the continuation is not owned by the plugin and there is a possibility of other plugins overwriting your data. (not a really big problem if you own all the code)

**Comment by bryancall** [comment]
If this is still an issue please reopen.
