### ISSUE TITLE
Larger downloads over H2 stalls with #2881 and priorities enabled

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#3077]
On Docs (with #2881 enabled, currently it is not) a command like this will hang every time, at exactly 55.8% (which is really, really close to 1MB).

```
curl  -D - -o /dev/null  https://ci.trafficserver.apache.org/bintray/clang-format-20170404.tar.bz2
```

This is with a "curl" client that supports H2. I tracked this down to the commit from #2881, which unfortunately is also back ported to 7.1.3. Reverting this change on master seems to fix the issue.

The remap rule for the above is

```
map https://ci.trafficserver.apache.org/bintray https://bintray.com/artifact/download/apache/trafficserver
```

**Comment by shinrich** [comment]
I tried writing a test for this, but unfortunately, I cannot reproduce the stall with ATS and my client running on the same box.  Give the nature of #2881 I assume that it is triggered by larger times between client and ATS.  For larger files there will be pauses as the H2 windows are exhausted.

I am currently downloading a ISO file through ATS with #2881 enabled and it is chunking along.  800MB downloaded so far.  But again my client and ATS are on the same RHEL7 box.

I'll go ahead and get the h2big test expanded, but probably not tonight.  I need to play with the timeouts, and I'm seeing something odd with a next_no_activity_timeout being set to 0.  I'll open another issue for that if it is something real.  I think it is separate from this issue.

In the short term, it would probably be best to revert #2881 at least from the 7.1.x branch until we figure out what is going on.

**Comment by masaori335** [comment]
I tried master and 7.1.x branch with #2881, but I couldn't reproduce this issue either. I'm missing something to reproduce :/

FWIW, what I tried is below.
1) With origin server which has static files (1MB, 10MB, and 100MB), I could download all of them through ATS regardless cache hit or miss. 
2) With the remap rule of downloading clang-format from bintray.com, I didn't see the stall and the check sum of the file was correct.

**Comment by zwoop** [comment]
We can try again on Docs, maybe there's something else intervening together with that patch.. Note that it's only with H2 requests this happens.

**Comment by zwoop** [comment]
I've restored the "broken" behavior on Docs / Ci again, e.g. this hangs at 55% always (with a curl that supports H2):

curl  -D - -o /dev/null  https://ci.trafficserver.apache.org/bintray/clang-format-20170404.tar.bz2

**Comment by zwoop** [comment]
Seems it's related to priorities, I did some tracing, and it seems strange around the priorities. I turned off the H2 priorities feature (in records.config), and then it works again.

**Comment by masaori335** [comment]
As far as I understand, the scenario of this stall is below. 

0. H2 priorities feature is enabled
1. When `write_vio` of Http2Stream is filled (`write_vio.get_writer()->write_avail()` is zero) and `Http2Stream::send_response_body()` is called from `Http2Stream::update_write_request()`, `send_response_body()` schedule ` HTTP2_SESSION_EVENT_XMIT` event. This means the `write_vio` is not consumed immediately.
2. After `Http2Stream::send_response_body()` is called, `VC_EVENT_WRITE_READY` event is send to `write_vio._cont` (`HttpTunnel`)
3. `HttpTunnel` doesn't read anything from origin server side, because `write_vio` is not consumed.

Below patch mitigate this issue and proof the above scenario by sending `VC_EVENT_WRITE_READY` event when `write_vio` is consumed.

https://paste.apache.org/fQsT

But I'm not confident that adding this code in `Http2Stream::update_sent_count()` is suitable. Let me think more.
