### ISSUE TITLE
Overriding client cert with TSHttpOverridableConfig API has no effect

### ISSUE THREAD

**Issue by camr2** [apache/trafficserver#3103]
I am developing a plugin for 7.1.0. I'm trying to use the TSHttpOverridableConfig methods to override proxy.config.ssl.client.cert.filename/path configuration for certain transactions but the API has no effect. This seems to be because SSL context initialization function is using the configured path instead of the overridden one. I created the following patch to work around this:

```
--- ./iocore/net/P_SSLClientUtils.h 2018-02-09 17:09:37.000000000 0000
+++ ./iocore/net/P_SSLClientUtils.h 2018-02-09 17:27:57.000000000 0000
@@ -36,6 +36,7 @@
 
 // Create and initialize a SSL client context.
 SSL_CTX *SSLInitClientContext(const struct SSLConfigParams *param);
+SSL_CTX *SSLInitClientContextWithCert(const struct SSLConfigParams *param, char *certFilePath);
 
 int verify_callback(int preverify_ok, X509_STORE_CTX *ctx);
 
--- ./iocore/net/SSLClientUtils.cc  2018-02-09 17:09:37.000000000 0000
+++ ./iocore/net/SSLClientUtils.cc  2018-02-09 17:27:57.000000000 0000
@@ -94,10 +94,20 @@
 SSL_CTX *
 SSLInitClientContext(const SSLConfigParams *params)
 {
+    return SSLInitClientContextWithCert(params, nullptr);
+}
+
+SSL_CTX *
+SSLInitClientContextWithCert(const SSLConfigParams *params, char *certFilePath)
+{
   ink_ssl_method_t meth = nullptr;
   SSL_CTX *client_ctx   = nullptr;
   char *clientKeyPtr    = nullptr;
 
+  if (certFilePath == nullptr) {
+      certFilePath = params->clientCertPath;
+  }
+
   // Note that we do not call RAND_seed() explicitly here, we depend on OpenSSL
   // to do the seeding of the PRNG for us. This is the case for all platforms that
   // has /dev/urandom for example.
@@ -126,12 +136,12 @@
   // assume it is contained in the client certificate file.
   clientKeyPtr = params->clientKeyPath;
   if (clientKeyPtr == nullptr) {
-    clientKeyPtr = params->clientCertPath;
+    clientKeyPtr = certFilePath;
   }
 
-  if (params->clientCertPath != nullptr && params->clientCertPath[0] != '\0') {
-    if (!SSL_CTX_use_certificate_chain_file(client_ctx, params->clientCertPath)) {
-      SSLError("failed to load client certificate from %s", params->clientCertPath);
+  if (certFilePath != nullptr && certFilePath[0] != '\0') {
+    if (!SSL_CTX_use_certificate_chain_file(client_ctx, certFilePath)) {
+      SSLError("failed to load client certificate from %s", certFilePath);
       goto fail;
     }
 
@@ -141,7 +151,7 @@
     }
 
     if (!SSL_CTX_check_private_key(client_ctx)) {
-      SSLError("client private key (%s) does not match the certificate public key (%s)", clientKeyPtr, params->clientCertPath);
+      SSLError("client private key (%s) does not match the certificate public key (%s)", clientKeyPtr, certFilePath);
       goto fail;
     }
   }
--- ./iocore/net/SSLConfig.cc 2018-02-09 17:09:37.000000000 0000
+++ ./iocore/net/SSLConfig.cc 2018-02-09 17:27:57.000000000 0000
@@ -399,7 +399,7 @@
 SSLConfigParams::getNewCTX(char *client_cert) const
 {
   SSL_CTX *nclient_ctx = nullptr;
-  nclient_ctx          = SSLInitClientContext(this);
+  nclient_ctx          = SSLInitClientContextWithCert(this, client_cert);
   if (!nclient_ctx) {
     SSLError("Can't initialize the SSL client, HTTPS in remap rules will not function");
     return nullptr;
```

**Comment by persiaAziz** [comment]
The way the overridable client cert path work is that it pulls the context from a map maintained internally. i.e., if you set the client cert path via a remap plugin, that should be used while making the actual connection with the origin server. The client cert path is more like a server property rather than a transaction specific config from ATS's point of view. 
You might want to look at apache/trafficserver to understand how it works in 7. 
Note: From 8.0 you can set the client cert using ssl_servername.config. 



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
apache/trafficserver

trafficserver - Mirror of Apache Traffic Server
 |

 |

 |






Syeda Persia Aziz
Software DeveloperYahoo! Inc.Champaign, Illinois 

    On Friday, February 9, 2018, 1:24:21 PM CST, camr2 <notifications@github.com> wrote:  
 
 
I am developing a plugin for 7.1.0. I'm trying to use the TSHttpOverridableConfig methods to override proxy.config.ssl.client.cert.filename/path configuration for certain transactions but the API has no effect. This seems to be because SSL context initialization function is using the configured path instead of the overridden one. I created the following patch to work around this:
--- ./iocore/net/P_SSLClientUtils.h 2018-02-09 17:09:37.000000000 0000
+++ ./iocore/net/P_SSLClientUtils.h 2018-02-09 17:27:57.000000000 0000
@@ -36,6 +36,7 @@
 
 // Create and initialize a SSL client context.
 SSL_CTX *SSLInitClientContext(const struct SSLConfigParams *param);
+SSL_CTX *SSLInitClientContextWithCert(const struct SSLConfigParams *param, char *certFilePath);
 
 int verify_callback(int preverify_ok, X509_STORE_CTX *ctx);
 
--- ./iocore/net/SSLClientUtils.cc  2018-02-09 17:09:37.000000000 0000
+++ ./iocore/net/SSLClientUtils.cc  2018-02-09 17:27:57.000000000 0000
@@ -94,10 +94,20 @@
 SSL_CTX *
 SSLInitClientContext(const SSLConfigParams *params)
 {
+    return SSLInitClientContextWithCert(params, nullptr);
+}
+
+SSL_CTX *
+SSLInitClientContextWithCert(const SSLConfigParams *params, char *certFilePath)
+{
   ink_ssl_method_t meth = nullptr;
   SSL_CTX *client_ctx   = nullptr;
   char *clientKeyPtr    = nullptr;
 
+  if (certFilePath == nullptr) {
+      certFilePath = params->clientCertPath;
+  }
+
   // Note that we do not call RAND_seed() explicitly here, we depend on OpenSSL
   // to do the seeding of the PRNG for us. This is the case for all platforms that
   // has /dev/urandom for example.
@@ -126,12 +136,12 @@
   // assume it is contained in the client certificate file.
   clientKeyPtr = params->clientKeyPath;
   if (clientKeyPtr == nullptr) {
-    clientKeyPtr = params->clientCertPath;
+    clientKeyPtr = certFilePath;
   }
 
-  if (params->clientCertPath != nullptr && params->clientCertPath[0] != '\0') {
-    if (!SSL_CTX_use_certificate_chain_file(client_ctx, params->clientCertPath)) {
-      SSLError("failed to load client certificate from %s", params->clientCertPath);
+  if (certFilePath != nullptr && certFilePath[0] != '\0') {
+    if (!SSL_CTX_use_certificate_chain_file(client_ctx, certFilePath)) {
+      SSLError("failed to load client certificate from %s", certFilePath);
       goto fail;
     }
 
@@ -141,7 +151,7 @@
     }
 
     if (!SSL_CTX_check_private_key(client_ctx)) {
-      SSLError("client private key (%s) does not match the certificate public key (%s)", clientKeyPtr, params->clientCertPath);
+      SSLError("client private key (%s) does not match the certificate public key (%s)", clientKeyPtr, certFilePath);
       goto fail;
     }
   }
--- ./iocore/net/SSLConfig.cc 2018-02-09 17:09:37.000000000 0000
+++ ./iocore/net/SSLConfig.cc 2018-02-09 17:27:57.000000000 0000
@@ -399,7 +399,7 @@
 SSLConfigParams::getNewCTX(char *client_cert) const
 {
   SSL_CTX *nclient_ctx = nullptr;
-  nclient_ctx          = SSLInitClientContext(this);
+  nclient_ctx          = SSLInitClientContextWithCert(this, client_cert);
   if (!nclient_ctx) {
     SSLError("Can't initialize the SSL client, HTTPS in remap rules will not function");
     return nullptr;

**Comment by camr2** [comment]
Thank you for the response. Are you saying that the TSHttpOverridableConfig API won't work in 7 to set the client cert path per transaction? I tried creating a remap pugin and calling the same API but got the same result. The cert from records.config is not overridden.

**Comment by persiaAziz** [comment]
Can you please paste the API and the TSOverridableConfigKey you are using to override the client cert. I see that the code for overriding the config is present in ATS. So the API should work. I wonder if something is wrong with the overridableconfigkey.

**Comment by zwoop** [comment]
At a minimum, you are using the wrong define, it should be e.g. 

```
TS_CONFIG_SSL_CLIENT_CERT_FILENAME.
```

**Comment by bryancall** [comment]
If this is still an issue please reopen.
