### ISSUE TITLE
Enable Parent Proxy only if parent_proxy_routing_enable is 1

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3157]
When some rules are written in `parent.config`, they are parsed and some parent proxy specific features are kicked regardless the value of `proxy.config.http.parent_proxy_routing_enable`. We noticed this during tracking #3100. 
This behavior makes confusions. Also this is different from what ATS Docs says.

> Traffic Server uses the parent.config file only when the parent caching option is enabled

https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/parent.config.en.html

**Comment by vmamidi** [comment]
I don't think we need this variable. rules in parent.config should be good enough to enable parent.

@mlibbey @zwoop @jrushford is it okay if I get rid of this variable?

**Comment by jrushford** [comment]
@mlibbey, @vmamidi, and @zwoop I'd be okay with getting rid of it. I think it's only checked in ParentSelection::findParent() and returns immediately if not enabled.  If it is enabled it checks to see if the request matches an entry in parent.config.  If no match is found it just returns a result to go direct to the origin.  so that request match lookup should be good enough.

**Comment by vmamidi** [comment]
#5570 removes the configuration variable.
