### ISSUE TITLE
Send close frame packet when we are in closing period

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3159]
>7.9.3. Immediate Close
>During the closing period, an endpoint that sends a closing frame SHOULD respond to any packet that it receives with another packet containing a closing frame.

Currently only close frame will be processed by QUICNetVConnection.

**Comment by maskit** [comment]
I don't think all frames need to be processed by QUICNetVC. Because the spec says the receiver should respond to any *packets*. Received frames probably have to be processed by appropriate frame handlers but QUICNetVC can simply send/resend a packet containing a closing frame after passing all frames to the frame dispatcher.

So what we need to do would be introducing `_state_connection_closing_process_packet()`, which calls `transmit_packet()` after `_recv_and_ack()`. Then WRITE_READY event will be scheduled and `_state_closing_send_packet()` will send the packet containing a closing frame.

**Comment by scw00** [comment]
Yes I agree !

**Comment by maskit** [comment]
Done with #3166.
