### ISSUE TITLE
How to flush cache data to Disk?

### ISSUE THREAD

**Issue by sangli00** [apache/trafficserver#3496]
I restart traffic Server,cache data is lose ,How to flush cache data to disk?

**Comment by mlibbey** [comment]
This is unusual to say the least -- the cache is persistent across restarts and even new version installs. Were you seeing cache hits before the restart? (What are proxy.node.cache.bytes_total_mb and proxy.node.cache.bytes_free_mb ?) Are you only using a RAM disk? Are you running the traffic_server binary with -K to clear the cache?

**Comment by sangli00** [comment]
I not only useing RAM disk.
if ```CONFIG proxy.config.cache.ram_cache.size INT 0 ``` ,TrafficServer is not cache any data ?

**Comment by SolidWallOfCode** [comment]
If you set the ram disk size to zero, TS still caches. There is a delay between when the object is cached and it is persistently on the disk because the directory index which tracks the cached objects is only written every few minutes. It can't be flushed more often without severe performance penalties.

**Comment by bryancall** [comment]
This is how ATS operates.  You need to wait for the disk cache to flush.
