### ISSUE TITLE
proxy.process.https.total_client_connections does not include Http2 connections

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#3513]
It is incremented in Http1ClientSession

**Comment by shinrich** [comment]
Same issue is true for the other total_client_connection counts for ipv4, ipv6, and overall connection counts.

I noticed there is already proxy.process.http2.total_client_connections.  We could go two ways.  We could add the https, ipv4, ipv6 to the proxy.process.http2 as well.

Or we could sink down these stats to proxy.process.net and store these connection statics independently of the version of HTTP (or other protocol) sitting on top of them.

**Comment by masaori335** [comment]
There're are confusions around metrics of http/https/http2. It looks good idea that storing these stats independently and aggregating them in metrics.config.

One concern is `proxy.process.net` looks not suitable name for these metrics, because it already has metrics for tcp. But I don't have good idea, so I'm fine with using it.

**Comment by masaori335** [comment]
`proxy.process.http.current_client_connections` looks also incremented in `Http1ClientSession` only. H2 has `proxy.process.http2.current_client_sessions`. ( obviously, this should be "connections" for consistency. )

**Comment by masaori335** [comment]
#4415 would fix this with other HTTP metric changes.

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
