### ISSUE TITLE
how to push doc with multi alternates for same url

### ISSUE THREAD

**Issue by ZiJinMountain** [apache/trafficserver#3649]
ATS support multi alternates for one url. But when I PUSH doc for same url with "curl", i found still only one alternate in cache. previous one from orignal server had been covered. 
Then checked code for this issue, i found in "HttpSM::do_cache_prepare_action" func, "bool allow_multiple" param is "false" by default. that is the reason of previous record covered. 
i try to find a way to generate multi alternates, but failed. 
Is there any way to generate multi alternates, one from original server, others from PUSH method?
The default value of "bool allow_multiple" in "HttpSM::do_cache_prepare_action" func can be changed or not ? 
kindly help for this issue, thank you.

**Comment by bryancall** [comment]
Unfortunately, I don't think anyone is interested in working on pushing alternates into cache.  I will ask at my work and see.

Most people are fetching object through ATS, since it is safer and there is no mistake in pushing the wrong object for a given URL.

**Comment by bryancall** [comment]
I talked to a few people about this issue and the feeling was it is safer to pull the requests into cache using GET instead of pushing objects into cache, since it would be the same behavior as fetching the object normally.

If you would like to supply a code change to support multiple alternates, then we would accept the change if it is not too invasive.  Please reopen if you are willing to make the change.
