### ISSUE TITLE
Better unsupported version packet handling

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3785]
If received packet is unsupported version, we can use only Version-Independent Properties written in https://tools.ietf.org/html/draft-ietf-quic-invariants-01.  I did some fixes for workaround (https://github.com/apache/trafficserver/commit/0a9fe522731ca820901781b08c6f9f892870e757), but current code looks complicated and fragile.
Currently, version is checked and sending VN in QUICHandshake::start(). IMO, we should do this in lower layer like QUICPacketHandler.

**Comment by maskit** [comment]
I don't think QUICPacketHandler itself or other classes should handle version negotiation. QUICPacketHandler should be only responsible for routing packets between sockets and NetVCs. We may be able to move QUICHandshake to lower layer in the future because of stream 0 changes, but it should keep responsible for version negotiation and it should provide a version which other components have to use. All components except QUICHandshake should pick appropriate implementations that can handle things based on the negotiated version.

**Comment by masaori335** [comment]
Talked offline, we agreed that unsupported version packet should be handled in QUICPacketHandlerIn. Because when version is unmatched, we don't know what type packet it is. And we found current code has a race of sending VN vs CONNECTION_CLOSE on HS.

Fixed by https://github.com/apache/trafficserver/commit/dbdd3d29115d11d474c3d18c2474c0cd530b5a24 and https://github.com/apache/trafficserver/commit/ac60e738390cb19871955a3017c1f14bd7cf5297
