### ISSUE TITLE
Certificates not reloaded unless ssl_multicert.config is touched

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#3931]
Certificates that are pointed to by `ssl_multicert.config` can change, but ATS only reloads them if the timestamp on `ssl_multicert.config` is updated, which may not change as certificates do.

The current work-around is to update the timestamp via a tool like `touch` to trigger reloading of the current certificates.

It would be nice to reload the config if the certificate files are changed, since it is confusing to admins who expect certificates to be reloaded while the server is up.

Related to #1672

**Comment by zizhong** [comment]
I remember I had a patch to address this. Not sure why it's not functioning. You can check https://github.com/apache/trafficserver/pull/301/files.
I'd take a look when I got time.

**Comment by d2r** [comment]
This is still a valid issue.

**Comment by shinrich** [comment]
I'll take a look at @zizhong's logic.  I've been through there recently.  Hopefully we just need to tweak something small to get the watching signaling propagating correctly.  

Now that we are also referencing and reloading client cert and key files in ssl_server_name.yaml, would be good to use a similar technique there.

**Comment by bryancall** [comment]
The change went into commit: 4d2c262c3be3bbcbfce3214826ecb16dee2cd027

**Comment by shinrich** [comment]
I verified that you no longer have to touch the ssl_multicert.config file if a referenced file is updated.  Getting ready to add an autest to exercise that case.  I thought it went in with my recent PR #6609, but looking at @zizhong's commit, all my PR did was rearrange what he had already added, so the fix is likely in whatever versions include   https://github.com/apache/trafficserver/commit/4d2c262c3be3bbcbfce3214826ecb16dee2cd027
