### ISSUE TITLE
Make proxy.config.http.redirect.actions overridable

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#4252]
#4145 Added a new config `proxy.config.http.redirect.actions`. [It would be nice](https://lists.apache.org/thread.html/673f0a0b088976529473008526885bf6c2f06a835c7d0ef3829366d6@%3Cdev.trafficserver.apache.org%3E) to make this configuration value overridable per transaction.

**Comment by d2r** [comment]
This is still a valid feature request.

**Comment by zwoop** [comment]
This is kinda difficult to make overridable, because it has to be parsed after records.config is parsed, and after someone overrides it as well. The more I see these custom parsers for config strings that are in records.config, the more I dislike it. I think with the migration to YAML, we can / should move such records.config settings into the remap.yaml config, we really shouldn't have custom config parsers at all, for individual settings.

**Comment by d2r** [comment]
I think @zwoop had the original suggestion for this. If we no longer want it to be overridable, then we can close the PR.

**Comment by zwoop** [comment]
I think we’d want it, just the whole custom parsing of configs within configs makes things complicated. Bit fields for the win!!

**Comment by SolidWallOfCode** [comment]
I think this is the wrong approach. This setting is an entire map. Instead there should be a plugin API call to directly set the redirect action for the transaction. That is, the core looks up the action via this (non-overridable) setting and then a plugin can directly change the value from the lookup, rather than changing the entire lookup table.
