### ISSUE TITLE
disable metrics in EventLoop in release version

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#4826]
Now, in EThread::execute_regular() every loop will do metrics collection. I understand these metrics are super useful when doing performance tuning.
But in the other cases, they are a waste of CPU, even they are only a few cycles.

The ASM of these statement looks like
```
        test    esi, esi
        jle     .L3
        cmp     DWORD PTR [rdi], esi
        jge     .L4
        mov     DWORD PTR [rdi], esi
.L4:
        cmp     DWORD PTR [rdi+4], esi
        jg      .L9
.L3:
        cmp     DWORD PTR [rdi+16], edx
        jle     .L6
        mov     DWORD PTR [rdi+16], edx
.L6:
        cmp     DWORD PTR [rdi+12], edx
        jge     .L7
        mov     DWORD PTR [rdi+12], edx
.L7:
        add     DWORD PTR [rdi+20], edx
        ret
.L9:
        mov     DWORD PTR [rdi+4], esi
        jmp     .L3
```

And remember they are running for evevy event loop.

**Comment by zizhong** [comment]
@SolidWallOfCode

**Comment by SolidWallOfCode** [comment]
We've considered that, but in various production environments there has been no apparent effect. If you look at the data, you can see than a single event loop iteration takes 5-20 ms. The total time for these instructions would be 5-20 ns. It's difficult for me to see how this could have any noticeable performance impact. I made an explicit effort to minimize the impact of this data gathering.

We certainly won't disable them in release mode, because in production is where we get the most use out of the data. It might be reasonable to make it a configure option, so that TS can be built without the metrics.

**Comment by SolidWallOfCode** [comment]
We've decided to close this, but if you want to make a configure time option, that would likely be accepted.
