### ISSUE TITLE
Lua plugin error: undefined symbol: lua_gettop

### ISSUE THREAD

**Issue by DrmagicE** [apache/trafficserver#5158]
I'm trying to use redis with lua plugin:
```
require('redis')
local redis = require 'redis'
local client = redis.connect('127.0.0.1', 6379)
local response = client:ping()  

.... 
```
and got the error message below:
```
ERROR: [ReverseProxy] failed to add remap rule at /opt/ats/etc/trafficserver/remap.config line 196: 
Failed to create instance for plugin "/opt/ats/libexec/trafficserver/tslua.so": 
[ts_lua_add_module] lua_pcall /opt/ats/etc/trafficserver/script/test_global_hdr.lua failed: 
error loading module 'socket.core' from file '/usr/local/lib/lua/5.1/socket/core.so':
/usr/local/lib/lua/5.1/socket/core.so: undefined symbol: lua_gettop
```

`require('redis')`  works in luajit.

How can i fix that ? 

Version :
Trafficserver 8.0
Luajit 2.0.5
Lua 5.1.4

OS:
CentOS 7

**Comment by shukitchan** [comment]
There is another person on the mailing list asking a similar question.

Let me try it out tonight and see.

**Comment by shukitchan** [comment]
Ok. I tried to reproduce this with a fresh ubuntu genial vm (latest TS on master, luajit-2.0.5, luasocket-2.0.2, redis-lua-2.0.4) and yes, I can reproduce that. 

Here are some points
1) I have used luasocket before and it worked. The reason is that luasocket is compiled to not dynamic linked to Lua library. Instead it relied on the caller of luasocket to have those symbols/references exposed. So it worked great for previous version of ATS because we were bringing in luajit into the core. Starting a few months ago, we stopped doing that and instead we make the ats lua plugin to have a dynamic link requirement instead. So if you "require" luasocket in your lua script for the ats lua plugin, you will get the above error during start up

2) I get it to work with my fresh new setup by compiling luasocket differently. Specifically inside src/Makefile, I added "-lluajit-5.1 -ldl -lm" at the end to all the LD lines that is responsible for generating the shared object (*.so).

**Comment by shukitchan** [comment]
Please let me know if it does not work.

**Comment by ezelkow1** [comment]
@shukitchan I ran in to this with the lua crypto library as well.  So another possible solution, if we add
lua_tslua_la_LDFLAGS += -lluajit-5.1

To the tslua Makefile.inc that forces the tslua.so to actually link against the luajit.so

**Comment by shukitchan** [comment]
You should not need that in lua_tslua_la_LDFLAGS because we have this - https://github.com/apache/trafficserver/blob/master/build/luajit.m4#L88

I tried out luacrypto-0.3.2 and I do a cmake and then make to generate the "so". I did a ldd and notice that it is dynamically linked to the lua library I installed on my vm (with ats master branch installed). And as expected, it won't work with the ats lua plugin. I changed to make it dynamically linked to luajit instead and it worked fine with the ATS lua plugin after that. 

@ezelkow1 , I don't understand how your problem got fixed still. When I run ldd against tslua.so , I can see luajit as a dependency. Also I think by default we need luajit installed to have tslua.so to be generated. Perhaps you can tell me a bit more on how your build env generates tslua.so ?

**Comment by shukitchan** [comment]
just saw your message on irc. so I think we are good then.

**Comment by ericchaves** [comment]
@shukitchan @ezelkow1 could you give me a hand to figure out what I'm missing? my build is still not working. The entire build process could be seen in this [dockerfile](https://github.com/ericchaves/ats-lua-playground/blob/feature/redis-plugin/trafficserver.dockerfile).

In short, I (think) patched the [luasocket src/makefile](https://github.com/ericchaves/ats-lua-playground/blob/feature/redis-plugin/patches/luasocket.patch) as @shukitchan suggested and also tried to patch the [tslua makefile](https://github.com/ericchaves/ats-lua-playground/blob/feature/redis-plugin/patches/tslua.patch) following @ezelkow1 but the tslua plugins still giving me the symbol error.

If I ran a simple [lua test script](https://github.com/ericchaves/ats-lua-playground/blob/feature/redis-plugin/plugins/test-redis.lua) using both lua or luajit I connect successfully into redis (making me belive that luasocket+redis-lua were installed ok).

However my [lua script plugin](https://github.com/ericchaves/ats-lua-playground/blob/feature/redis-plugin/plugins/my_module.lua) still raising the error:` ERROR: [ts_lua] lua_pcall failed: error loading module 'socket.core' from file '/usr/local/lib/lua/5.1/socket/core.so':
        /usr/local/lib/lua/5.1/socket/core.so: undefined symbol: lua_gettop`.

I'm using ATS 8.0.3, LuaJIT 2.0.5, LuaRocks 3.0.4 and Luasocket 3.0.rc1 (Luasocket is being compiled using luarocks after patching the src/makefile).

If needed you an replicate the error by cloning my repo and build/running ats with [docker-compose](https://github.com/ericchaves/ats-lua-playground/blob/feature/redis-plugin/docker-compose.yaml). All my testes were done from inside the docker container (`docker-compose up -d && docker-compose exec trafficserver /bin/bash`)

I really appreciate any help. =) cheers.

**Comment by ezelkow1** [comment]
For us it was the luacrypto library. What I had to do was start building the luacrypto library, with LDFLAGS=-lluajit-5.1. I then package that up in to our ats rpm so it gets distributed with it. Then had to modify the systemd script to set Environment=LUA_CPATH=/your/installpath/forlua/plugins, i.e. for us it was trafficserver/lua/crypto.so for the crypto plugin we packaged with our rpm

**Comment by ericchaves** [comment]
Finally I've figure it out! =) I was patching the luasocket src/makefile to make it properly export the symbols as you guys pointed out. But I was still using luarocks to build it and for some reason luarocks does not build it apply the patched parameters (not sure but it seems it build it for an invalid "unix" target instead of "linux").

To fix it what I did is to first  install luasocket and luaredis using luarocks (just because easier to install and control dependencies) and after that I manually build luasocket from source with patched src/makefile (make linux && make install) effectively replacing the socket.so libs with a properly built version.

Cheers =)

**Comment by Bharat786** [comment]
@shukitchan i did'nt understood this line, can you please help?

```
I get it to work with my fresh new setup by compiling luasocket differently. Specifically inside src/Makefile, I added "-lluajit-5.1 -ldl -lm" at the end to all the LD lines that is responsible for generating the shared object (*.so).
```

So should i build luasocket(in my use case it is lpeg) from the source code and edite the makefile with this line "-lluajit-5.1 -ldl -lm" ?

**Comment by shukitchan** [comment]
Yes. That's right.

**Comment by Bharat786** [comment]
@shukitchan Actually in the lpeg library source code there is no src/Makefile, so how should i do it : https://github.com/luvit/lpeg

**Comment by shukitchan** [comment]
@Bharat786 let's keep the conversation in #8222
