### ISSUE TITLE
Maybe adjust default value of the -m argument for easier upgrade experience

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#6472]
Due to changes in commit cba8b22ad5, the compile time constant for maxRecords is changed to a runtime constant.  The compile time constant was 2500.  The default (and minimum) size with the argument is 1600.  When we upgraded to 9.0, we got the following message every minute or so in diags.log

```
[Sep 25 21:00:46.121] [ET_NET 16] WARNING: too many stats/configs, please increase max_records_entries using the --maxRecords command line option
```

We fixed this by adding the -m 2500 option to our systemd service file. 

However, for a superior out of the box experience on upgrade, shouldn't the new default be the same as the old compile time constant?

**Comment by zizhong** [comment]
@15ljindal  encountered the same issue. In our case, we have another script to call the trafficserver script to start ATS.
It seems that [the current trafficserver ](https://github.com/apache/trafficserver/blob/cda2d845e638011e4c4854c4e3b355b48a43cdc5/rc/trafficserver.in)script doesn't take any parameters from the caller, which I think we can make a change, so that we don't need to maintain a local patch for our customized ATS parameters.

**Comment by zwoop** [comment]
Please close the issues associated with a PR.
