### ISSUE TITLE
Loop detection interferes with parent selection

### ISSUE THREAD

**Issue by mtorluemke** [apache/trafficserver#7052]
PR #5767 added a check such that a loop is detected if the client IP is the same as the cache IP. This breaks the case where the remap config is:

```
map http://foo.com http://foo.com
```

and, one uses parent selection with `go_direct=false` -- a loop is improperly detected.

**Comment by randall** [comment]
#5767 also breaks how we document using the `generator` plugin.

from https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/plugins/generator.en.html?highlight=generator#examples

```
map http://workload.example.com/ http://127.0.0.1/ \
  @plugin=generator.so
```

**Comment by SolidWallOfCode** [comment]
In progress.

**Comment by SolidWallOfCode** [comment]
See PR #7069

**Comment by SolidWallOfCode** [comment]
I didn't realize this wasn't well commented.

After an online discussion, it was decided the root of the problem was the self loop detection was done too early. In particular, it did not make sense to anyone that it was done immediately after the DNS lookup, which can happen before cache read. A bad side effect of this is that it can not only interfere with parent selection, but it fails to detect loops in parent selection precisely because it is done too early. The change to be made is to move the direct loop detection to `HttpSM::do_http_server_open` which is where the upstream connection is opened. There is already a slew of checks in that method which are done just before connecting, such as checking for an existing session, checking for too many connections, checking remap ACLs, etc. It seems natural that direct self loop detection should also be done in there.
