### ISSUE TITLE
[8.0.8] 400 Bad Request when pushing object into cache

### ISSUE THREAD

**Issue by Har-Kuun** [apache/trafficserver#7055]
As title suggests, I'm following the [guide here](https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/storage/index.en.html#pushing-an-object-into-the-cache) to push content into cache.

The PUSH method option has been enabled in `records.config`, and local IP is whitelisted in `ip_allow.config`.  ATS server is in reverse proxy mode, with https://example.com mapping the origin server IP.

The first step, `curl -s -i -o /path/to/file "https://example.com/push_me.html"` runs smoothly.

The second step in the guide, `curl -x -s -o /dev/null -X PUSH --data-binary /path/to/file "https://example.com/push_me.html"`, are causing probelms.  Directly running this command throws a `curl: (5) Could not resolve proxy:` error due to the `-x` option here.  Removing the -x option will lead to 400 Bad Request response from the origin server.  I'm wondering what is the correct way to do this.

Thank you!

**Comment by SolidWallOfCode** [comment]
I suspect the problem is that `curl` does proxying for HTTP and HTTPS different. In the first case `curl` does a TLS connect and sends the `PUSH`. If the `-x` or `--proxy` option is used with an HTTPS proxy then `curl` will send a `CONNECT` to the proxy and then send a `PUSH` to the upstream. Presuming "example.com" isn't ATS, then neither `curl` actually connects to ATS.

**Comment by bneradt** [comment]
The -x option should take a proxy URL. It sounds like the document had a bug in it. It looks like this document has since been updated to address the problem that was seen here. Please re-open if the current document is still confusing.
