### ISSUE TITLE
proxy.config.http.number_of_redirections with hit_stale

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#7200]
In testing ATS 9, one of our properties overrides proxy.config.http.number_of_redirections. When the object is stale in cache, ATS returns the 302 instead of chasing the redirect. It appears very reproducible for the 1 property that uses it.

**Comment by ywkaras** [comment]
I'm trying to look at this, but am a novice in this area, help welcome.

**Comment by mlibbey** [comment]
There are a few recent commits around this
#6589
#6561
#4962
#4902 
perhaps more too...

**Comment by ywkaras** [comment]
I think I've got a simple test that reproduces the problem.  Works in 8.1.x but not on master.
https://github.com/ywkaras/trafficserver/commit/7c1545f99de9d30c11a6ff813a675fdaa0282408

**Comment by ywkaras** [comment]
It looks like the change in behavior is due to the added call to HttpTransact::is_cache_hit() is the cause of the change in behavior:  https://github.com/apache/trafficserver/blob/bd089772b735bc374c0f0f4fedccabd1e6a30cda/proxy/http/HttpSM.cc#L8104 .
This call is not present in the 8.1.x code:  https://github.com/apache/trafficserver/blob/502ee35dd85a9f3f9936f886fc4e4d56507b7fbb/proxy/http/HttpSM.cc#L7959 .

**Comment by ywkaras** [comment]
This is the PR that introduced the above change:  https://github.com/apache/trafficserver/pull/4289 .  @SolidWallOfCode any insights?
