### ISSUE TITLE
Revalidation on range request leads to full object being served

### ISSUE THREAD

**Issue by elsloo** [apache/trafficserver#8161]
When a range request comes into ATS and the underlying object must be revalidated or is expired, it appears that ATS serves the entire object to the client and ignores the requested range in the `Range` header. While range requests are not required to be supported, in this case they are supported in ATS, and the difference in behavior can lead to unexpected results when the client sees the 200 and full object instead of the 206. Ideally ATS would revalidate, fill the new object as necessary, and return the requested range to the client.

**Comment by SolidWallOfCode** [comment]
The problem here is for a cached range the internals can do the fast range check and set up the CacheVC to fetch only the relevant fragments from disk. Therefore the producer streams only those fragments. If the object is revalidated then the producer stream is the entire object and there's no good way (currently) to impose the range view on that stream.

**Comment by vmamidi** [comment]
Serris Lew is going to start working on this. I have assigned to myself as i can't assign it to her.
