### ISSUE TITLE
Performance Tuning documentation page missing

### ISSUE THREAD

**Issue by djcarlin** [apache/trafficserver#8542]
I was looking up timeout settings docs:

https://docs.trafficserver.apache.org/records.config#proxy-config-http-keep-alive-no-activity-timeout-out

They all say "See Timeout Settings for more discussion on Traffic Server timeouts." but if you click on the link you get 404.

Should this https://docs.trafficserver.apache.org/records.config page even exist?  I was expecting something with a documentation version in the path:

https://docs.trafficserver.apache.org/en/9.1.x/

**Comment by ywkaras** [comment]
Dude, it's trafficserver.  I think you're getting unrealistic hopes cause I asked for a pony and actually got one.

**Comment by ezelkow1** [comment]
This came up during the CI rework. There are a handful of placeholders like that because some people, mainly @zwoop :), liked having those shorthand shortcuts to specific files. So we have specific remaps for specific files like that

We did have to fix them once already but maybe we are still missing some for them

**Comment by mlibbey** [comment]
Just had an internal report of the same. Google has the "bad" page as the first result for "ats records.config"

**Comment by bneradt** [comment]
Thanks for pointing this out Dave!

There's two unrelated things mentioned in this thread:

Should this https://docs.trafficserver.apache.org/records.config
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.trafficserver.apache.org_records.config&d=DwMCaQ&c=sWW_bEwW_mLyN3Kx2v57Q8e-CRbmiT9yOhqES_g_wVY&r=QqpSWgNGj0TQqWr3_U9U8a-TyrKRt3NR6Cr-LMDTUZE&m=BTSkUOqzmvd6nfkF3JY2ba0Z20zvKL2lHcON3iUvylg&s=jF8Wrl9rzw8O0_mkRTGzgt6oZvvBiEWw7geFXXuXIjU&e=>
>  page even exist? I was expecting something with a documentation version
> in the path:
>
This understandably looks strangely short, but this is fine. As Evan
pointed out, this is an intentionally configured shortcut that allows easy
linking to records.config documentation. The shortcut is in place because
it is frequently accessed.

They all say "See Timeout Settings for more discussion on Traffic Server
> timeouts." but if you click on the link you get 404.
>

This, on the other hand, is definitely not fine and it's a problem. In this
case that you point out, they are generated via
:ref:`admin-performance-timeouts` references in various places in our
records.config.en.rst code here:
https://github.com/apache/trafficserver/blame/master/doc/admin-guide/files/records.config.en.rst#L469

That label is defined here:
https://github.com/apache/trafficserver/blame/master/doc/admin-guide/performance/index.en.rst#L212


Here's another, different link to a different label that is broken:
https://docs.trafficserver.apache.org/records.config#overridable

Following the " Configuration Remap Plugin" link also results in a 404.

Are all our internal links to labels broken? I'll look into this.

**Comment by SolidWallOfCode** [comment]
The internals are fine and the relative links are fine. The problem is entirely landing on a page like "https://docs.trafficserver.apache.org/records.config". THAT IS WRONG. It should be "https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html". The result is the brower is using the wrong URL and does the relative computation incorrectly. I'm not sure Sphinx can be set to use absolute URLs because those are fundamentally unknowable at the time the documentation is generated.

**Comment by mlibbey** [comment]
where is the shortcut configured? I don't see a raw records.config in the /doc/docbuild/html/ after building; and I haven't been able to find it in source. Is it done in the docs ATS directly? (and if so, can we change it from map to redirect_temporary ?)

**Comment by bneradt** [comment]
I fixed this via httpd configuration settings. I removed the remap.config rule to handle the shortcut and configured redirection via httpd, as was done in the earlier CI configuration. This allows both the shortcuts to work and the links from pages that were loaded via a shortcut URL.

Thus, if you now follow this shortcut link:
https://docs.trafficserver.apache.org/records.config#proxy-config-http-keep-alive-no-activity-timeout-out

The link "Timeout Settings" now works.

Thank you @djcarlin for reporting this.
