### ISSUE TITLE
How can I implement CACHE conditions with header rewrite plugin?

### ISSUE THREAD

**Issue by amoghyermalkar123** [apache/trafficserver#8808]
I want to sort of mimic the X-debug plugin capabilites. My ATS version is 8.1.1 and the header rewrite plugin does not yet support the `${CACHE}` condition. Is there any way I can achieve the desired functionality on 8.1.1 ATS ? The thing is we have a fixed custom OS and ATS 10.0 can't be installed on it.

**Comment by dhairav** [comment]
Hi, we basically need to append the Cache Status responses - like how Cloudfront does - for example - 

`< x-cache: Miss from cloudfront
< x-amz-cf-pop: BOM51-C1
`

We are stuck with using ATS 8.1.1 since the Debian based systems we are using doesn't let us upgrade to ATS v9.x.x or the latest as of yet.

**Comment by shukitchan** [comment]
If you can use lua plugin, you can try this out- 

https://docs.trafficserver.apache.org/en/8.1.x/admin-guide/plugins/lua.en.html#ts-http-get-cache-lookup-status

**Comment by amoghyermalkar123** [comment]
Works @shukitchan, closing this.
