### ISSUE TITLE
Post a PURGE Request, when do we expect actual disk Object to be deleted?

### ISSUE THREAD

**Issue by dhairav** [apache/trafficserver#8984]
So, we're using ATS v8.1.1 as a caching server. Due to compliance purposes, we need to routinely purge certain objects out of the disks - per terms of license agreements with the owners of the HTTP objects.
It is mission critical for us to reclaim space from the disks - as soon as we PURGE certain objects, but as per the documentation for PURGE - it is clear that the objects are not deleted from the disks after a PURGE request,  exact excerpt from ATS docs - 

`This procedure only removes the index to the object from a specific Traffic Server cache. While the object remains on disk, Traffic Server will no longer able to find the object. The next request for that object will result in a fresh copy of the object fetched. Users may still see the old (removed) content if it was cached by intermediary caches or by the end-users’ web browser.`

Available at - https://docs.trafficserver.apache.org/en/8.1.x/admin-guide/storage/index.en.html#removing-an-object-from-the-cache

How do we delete from disk effectively? Is there a ready-made way? Or is there a way using the TS CacheRead or TS CacheRemove APIs in C/C++?

**Comment by mlibbey** [comment]
Do your license agreements force you to overwrite the disk for removed files (like secure remove)? As I understand it, removing the object's index is very similar to how a file system rm/empty trash works -- that the file is still there, just need to go to more severe lengths to recover. The hurdle for ATS would be much more severe as significant tool engineering development would be required.

**Comment by dhairav** [comment]
Well, no, the agreements simply need us to ensure that objects that shouldn't exist with us, are deleted. If you're saying that a PURGE request does an rm - similar to one on an ext4 file system over Linux - I think that should satisfy my use case.  
But in any case - do you think it is worthwhile to explore any C/C++ APIs for TS Find and Delete - or is it going to be too painful to implement due to the way ATS is supposed to function conceptually?
If it is possible - I would write a C/C++ plugin that would accept a Regular Expression string - try to search the cache index for the object(s) and invoke a TS Delete API (if one exists - and I'd appreciate your inputs here).

P.S. - Appreciate you taking out the time for answering this.

**Comment by mlibbey** [comment]
My understanding is that it would very painful. As I understand it ([here is a good doc about the cache](https://docs.trafficserver.apache.org/developer-guide/cache-architecture/architecture.en.html)), the objects are not stored in contiguous blocks. They are intertwined with the other objects that are being written at the same time -- the index gives the locations. Once the index is gone, the locations are gone (like the rm). So, I'd think you'd need to go walk the disk -- if you still know the bytes of the original file (and any alternates), then its probably a straightforward block by block search. If you just know the original hash, its a lot worse -- you need to gather all the fragments and start concatenating and testing (but, you don't know which fragment is the start -- so the combinations grow). Problem gets worse if the disk is in use -- the cache continues to change. So, probably it'd be better to encrypt the disk, and cycle the key (thus making the entire disk complete gibberish) every time there is purge, or (much slower), do the equivalent of the shred command to the disk, or go the hardware method, and exclusively use RAM disk, and just reboot the machine instead of purging.

**Comment by dhairav** [comment]
Makes sense, closing this, thank you so much @mlibbey!
