### ISSUE TITLE
Add qlog support for quiche

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#9343]

**Comment by maskit** [comment]
There are some code for QLog already but I'm not sure if it's working.

```
$ git grep qlog  | grep quiche
iocore/net/QUICPacketHandler_quiche.cc:    if (params->qlog_dir() != nullptr) {
iocore/net/QUICPacketHandler_quiche.cc:      char qlog_filepath[PATH_MAX];
iocore/net/QUICPacketHandler_quiche.cc:      sprintf(qlog_filepath, "%s/%.*s.sqlog", Layout::get()->relative(params->qlog_dir()).c_str(),
iocore/net/QUICPacketHandler_quiche.cc:      quiche_conn_set_qlog_path(quiche_con, qlog_filepath, "ats", "");
```

**Comment by brbzull0** [comment]
There isn't much control on our side as you said with the qlog,  the good think is that it works, I may add some error checks when calling quiche as I was testing with some invalid dir and I never knew. 

Also I think we should go for something like this in the config that can let us grow eventually and proivide a more granular configuration:
```yaml
ts:
  quic:
    qlog:
      base_name: /some/dir/test1
```
similiar to what provides `h2load`, 
```
--qlog-file-base=<PATH>                                                      
              Enable qlog output and specify base file name for qlogs.
              Qlog is emitted  for each connection.  For  a given base
              name   "base",    each   output   file    name   becomes         
              "base.M.N.sqlog" where M is worker ID and N is client ID
              (e.g. "base.0.3.sqlog").  Only effective in QUIC runs. 
```
You provide a base name, which may include a folder and ATS will append the  trace_id + the extension  to it, so we will end up with something like
`/some/dur/test1_b5c9cbf4d41cd60c779f059d749dd3cd5b8.sqlog`

1 - @maskit @bryancall  what do you guys think about the config change? It's currently `proxy.config.quic.qlog_dir`?

2 - Also, shouldn't we do this record overridable(conf_remap)? otherwise we may create tons of this if we aren't careful.

**Comment by maskit** [comment]
1. I'm fine with the config change. I don't remember current filename format, but the change would just makes /abc/xyz/123.qlog to /abc/xyz-123.qlog.
2. Yes, we need some control on that. Currently qlog is enabled by setting a path to config_dir and unsetting it disables qlog.  Having "ts.quic.qlog.enable" may make it easier to enable/disable qlog by conf_remap.

**Comment by brbzull0** [comment]
> 1. I'm fine with the config change. I don't remember current filename format, but the change would just makes /abc/xyz/123.qlog to /abc/xyz-123.qlog.

done https://github.com/apache/trafficserver/pull/9461


>  Having "ts.quic.qlog.enable" may make it easier to enable/disable qlog by conf_remap.

I have question on this regard,  isn't the config remap hook happening at a later stage than where we enable/disable qlogs?

**Comment by maskit** [comment]
Ah, right. We probably need SIN action for it instead.
