### ISSUE TITLE
9.2.x: tsapi autest core dumps on destruction

### ISSUE THREAD

**Issue by traeak** [apache/trafficserver#9914]
Seen in CI autests.
Removing the Cleanup() class declaration in test_tsapi.cc stops the crash.

**Comment by ywkaras** [comment]
I tried this in my Red Hat 8(ish) environment and it works fine with no changes.

**Comment by traeak** [comment]
It crashes consistently on my rockylinux 8 install.

**Comment by ywkaras** [comment]
I ran the test 20 times in a row in a docker cointainer running Rocky Linux 8, no failures.  (I built using commit b0028efff353a3abac83439b19511e4d59979b09 ).

**Comment by bneradt** [comment]
On master, the shutdown fix from @ywkaras address is this. That patch is not really compatible for 9.2.x though. I just pushed a fix for 9.2.x using a shut down handler rather than the global Cleanup class. I think we can close this ticket. @traeak : can you verify that things are working better now and close if this is no longer an issue?

**Comment by ywkaras** [comment]
Closed by merge of PR 9952.
