### ISSUE TITLE
How to config ATS to refresh cache for files modified on server

### ISSUE THREAD

**Issue by 2803media** [apache/trafficserver#9939]
Hi 

I run an ATS in production and I have files that are updated every day and a cache config of 60 days cache by default. I just want to know if it's possible to invalidate those files if the files are newly modify or if the simplest way is to exclude the files folder from the cache which is the worst way for me in a cache logic.

Thanks for your advise and example if you have somes

**Comment by mlibbey** [comment]
Guess a few best practices:
- Have the origin version assets when changed -- query strings; checksums in the path... something that makes the new content get a unique cache key. That way, new content is fetched once users start requesting it.
- Have the origin set the Cache-Control header instead of using cache.config to define the cache policy. 
- If versioning is not possible, have the origin set the max-age to how fast they need the new content to appear -- noting that shorter max-age times means more load on origin (and more frequent slower user experience). For example for daily content, they would be ok with content showing up within an hour after publishing -- then set max-age=3600.

You can purge individual objects with the PURGE method -- eg, curl -XPURGE "http://example.com/foo.jpg". You could also invalidate the entire cache for a remap rule via the [proxy.config.http.cache.generation]( https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-http-cache-generation) setting override. There is also a [Regex Revalidation Plugin](https://docs.trafficserver.apache.org/admin-guide/plugins/regex_revalidate.en.html) where you give a list of regexes to invalidate on the next request.

**Comment by 2803media** [comment]
@mlibbey is something like that relevant for you?

```
<IfModule mod_expires.c>
                ExpiresActive on
                ExpiresDefault "access plus 1 day"                         
                ExpiresByType image/jpg "access plus 60 days"
                ExpiresByType image/png "access plus 60 days"
                ExpiresByType image/gif "access plus 60 days"
                ExpiresByType image/jpeg "access plus 60 days"
                ExpiresByType image/webp "access plus 60 days"
                ExpiresByType text/css "access plus 1 days"
                ExpiresByType application/x-protobuf "access plus 60 days"
                ExpiresByType image/x-icon "access plus 1 month"
                ExpiresByType text/javascript "access plus 1 week"
                ExpiresByType application/x-javascript "access plus 1 week"
                ExpiresByType application/javascript "access plus 1 week"
        </IfModule>
        <filesMatch ".(css|jpg|jpeg|png|gif|js|ico|woff|woff2|ttf|svg|webp|pbf)$">
                Header set Cache-Control "max-age=8380800, public"
        </filesMatch>

//the specific rule for my content updated each day
        <LocationMatch "/data/daily*">
                <IfModule mod_expires.c>
                        ExpiresByType application/x-protobuf "access plus 1 hour"
                </IfModule>   
                Header set Cache-Control "max-age=3600, public"
        </LocationMatch>
```

**Comment by mlibbey** [comment]
From the above, worst case, the /data/daily* content would be stale for the first hour of the day (eg, if it gets revalidated right before the new content is made.

If the production process can't generated uniquely named objects (or in new folder paths; new query strings... something -- versioned objects are definitely the best of best practices) guess should have also noted that Expires: alone may be what you are looking for -- like `"modification plus 24 hours"` (if that's both correct syntax and the files are created exactly 24hrs later), would have the cached copies all go stale at an exact time.
- When Expires and Cache-Control headers are both present, Expires is ignored.
- Expires alone increases the necessity of keeping the cache node's time correct.
- With expires alone, a specific object on all the cache nodes' will go stale at the same time -- which can mean a thundering herd of requests.
- if the production process stops the 'yet to be produced' objects will be continuously stale, and origin requests would increase for that time period. For instance, if the /data/daily/imageoftheday.jpg expires 24hrs after being made, and it actually gets produced 26hrs later, you'd have 2 hours of requests to the cache nodes resulting in proxying to the origin for updated content.

**Comment by mlibbey** [comment]
Think we can close this.
